#!/bin/bash

# If someone else owns the directory, remove it using cleanup script
if [[ -d /var/tmp/dcs-get && ! -O /var/tmp/dcs-get ]]
then
	if [ "$(md5sum /var/tmp/dcs-get/cleanup)" == "a79206b7a10ee067912405d824875549  /var/tmp/dcs-get/cleanup" ]
	do
		/var/tmp/dcs-get/cleanup
	else
		echo "Someone has screwed with the cleanup script, hurt them."
	fi
fi

# If the directory doesn't exist create it, cleanup script and grab dcs-get script
if [ ! -d /var/tmp/dcs-get ]
then
	mkdir /var/tmp/dcs-get
	chmod a+rX /var/tmp/dcs-get
	cd /var/tmp/dcs-get
	mkdir bin
	mkdir lib
	mkdir downloads
	mkdir downloaded
	touch cleanup
	echo "#!/usr/bin/perl" >> cleanup
	echo "use File::Path 'rmtree';" >> cleanup
	echo "rmtree([ '/var/tmp/dcs-get' ]);" >> cleanup
	chmod a+rx cleanup
	chmod ug+s cleanup
	# Get dcs-get
	cd bin
	wget -q http://backus.uwcs.co.uk/dcs-get/dcs-get
	chmod u+x dcs-get
fi
